PerformHttpRequest("https://02oo5xe6f2.execute-api.us-east-1.amazonaws.com/dev/counter", function (statusCode, data, headers)
    print("status code: " .. tostring(statusCode))
    print("data: " .. tostring(data))
    print("headers: " .. tostring(headers))
end)